# Use an official Python runtime as a parent image
FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy the requirement
COPY ./requirements.txt ./requirements.base.txt ./requirements.postgres.txt /app/

# Install any needed packages specified in requirements.txt
RUN  pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY ewallet/* /app
RUN ls /app
# Make port 8000 available to the world outside this container
EXPOSE 8000

# Add permission to entrypoint
RUN chmod +x /app/entrypoint.sh

# Define the command to run your application
ENTRYPOINT ["/app/entrypoint.sh"]
